kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-service-client
  labels:
    app: hello-service-client
data:
  application.yml: |
    hello-service:
      uri: http://helloservice:8080/hello-service/hello/
    spring:
      application:
        name: helloservice-client
      cloud:
        consul:
          host: http://consul-headless
          port: 8500
          discovery:
            preferIpAddress: true
            healthCheckInterval: 15s
            healthCheckPath: /hello-service-client/actuator/health
            health-check-url: http://hello-service-client:8080/hello-service-client/actuator/health
    server:
      servlet:
        context-path: /hello-service-client

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-service-client
  labels:
    app: hello-service-client
spec:
  selector:
    matchLabels:
      app: hello-service-client
  template:
    metadata:
      labels:
        app: hello-service-client
    spec:
      volumes:
        - name: application-config
          configMap:
            name: hello-service-client
      containers:
        - name: application
          image: mrflick72/consule-spike_hello-service-client:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /usr/local/hello-service-client/application.yml
              subPath: application.yml
              name: application-config
---

apiVersion: v1
kind: Service
metadata:
  name: hello-service-client
  labels:
    app: hello-service-client
spec:
  selector:
    app: hello-service-client
  ports:
    - port: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-service-client
  labels:
    app: hello-service-client
spec:
  rules:
    - http:
        paths:
          - path: /hello-service-client
            pathType: Prefix
            backend:
              service:
                name: hello-service-client
                port:
                  number: 8080